import "@/assets/style/global.css";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth, db } from "../config/firebase";
import type { AppProps } from "next/app";
import Home from "./login";
import { useEffect } from "react";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import Head from "next/head";
import SideBar from "@/components/sideBar";
import { ChatProvider } from "@/context/chatContext";
import { AuthProvider } from "@/context/AuthContext";
function MyApp({ Component, pageProps }: AppProps) {
  const [loggedInUser] = useAuthState(auth);
  useEffect(() => {
    const setUserInDb = async () => {
      try {
        await setDoc(
          doc(db, "users", loggedInUser?.email as string),
          {
            email: loggedInUser?.email,
            Password: loggedInUser?.toJSON,
            lastSeen: serverTimestamp(),
            photoURL: loggedInUser?.photoURL,
          },
          { merge: true }
        );
      } catch (error) {
        console.log("ERROR SETTING USER INFO IN DB", error);
      }
    };

    if (loggedInUser) {
      setUserInDb();
    }
  }, [loggedInUser]);
  if (!loggedInUser) return <Home />;

  return (
    <div className="flex">
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by Henry Web Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
      <AuthProvider>
        <ChatProvider>
          <Component {...pageProps} />
        </ChatProvider>
      </AuthProvider>
    </div>
  );
}

export default MyApp;
