import SideBar from "@/components/sideBar";
import type { NextPage } from "next";
import Head from "next/head";
const SIDE: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by Henry Web Dev" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SideBar />
    </div>
  );
};

export default SIDE;
